version: "3.9"
services:
    pcb-analysis-server:
        build: ./pcb-analysis
        ports:
            - "${LISTEN_ADDRESS}:5001:5001"
    signal-analysis-server:
        build: ./signal-analysis
        ports:
            - "${LISTEN_ADDRESS}:5002:5002"

